### ISSUE TITLE
data_failure

### ISSUE THREAD

**Issue by JR-Hub** [Avik-Jain/100-Days-Of-ML-Code#12]
**Describe the bug**

**To Reproduce**
on my computer there is a bug that says:
could not convert string to float: 'Germany'
could not convert string to float: 'France'

**Comment by yyfhaku** [comment]
It's amazing ,I never meet a question like that.

**Comment by SifanStephanie** [comment]
First check ur code again, perhaps you miss something like LabelEncoder()...

Second, maybe you can find more at https://stackoverflow.com/questions/30384995/randomforestclassfier-fit-valueerror-could-not-convert-string-to-float

Hope this would help :)
